name: Theomachy
version: '${version}'
main: org.Theomachy.Theomachy
api-version: '1.20'
libraries:
  - "net.kyori:adventure-platform-bukkit:4.3.2"
  - "net.kyori:adventure-api:4.15.0"
  - "com.elmakers.mine.bukkit:EffectLib:10.2"
commands:
  t:
    description: 'Your command description'
    usage: '/t <subcommand>'
  x:
    description: 'Your command description'
    usage: '/x <subcommand>'

# kyori 및 effectLib 라이브러리 사용
# https://www.youtube.com/watch?v=JirkSrw4FLU&list=PL1RKumEd8x5Y58_eW91l991Tn5BqmNGMp