name: Theomachy
version: '${version}'
main: org.septagram.Theomachy.Theomachy
api-version: '1.20'
commands:
  t:
    description: 'Your command description'
    usage: '/t <subcommand>'
  x:
    description: 'Your command description'
    usage: '/x <subcommand>'

