package org.septagram.Theomachy.Ability.ENUM;

import org.septagram.Theomachy.DB.GameData;

public enum AbilityCode {
    Zeus,
    Poseidon,
    Hades,
    Demeter,
    Athena,
    Apollon,
    Artemis,
    Ares,
    Hephastus,
    Asclepius,
    Hermes,
    Dionysus,
    Aprodite,
    Eris,
    Morpious,
    Aeolus,
    Akasha,
    Horeundal,
    Sans,

    //========================================================================================================


    Archer,
    Miner,
    Stance,
    Teleporter,
    Bomber,
    Creeper,
    Wizard,
    Assasin,
    Reflection,
    Blinder,
    Invincibility,
    Clocking,
    BlackSmith,
    Boxer,
    Priest,
    Witch,
    Meteor,
    Sniper,
    Voodoo,
    Anorexia,
    Bulter,
    Midoriya,
    Goldspoon,
    Bee,
    Snow,
    Tajja,
    AGirl,
    Megumin,
    PokeGo,
    Darkness,
    Gasolin,
    Zet;
}
